default: &default
  adapter: postgresql
  encoding: unicode
  collation: en_US.UTF-8
  pool: 5
  username: postgres
  password: ''
  host: localhost
  port: 5432

development:
  <<: *default
  database: rooms_dev

test:
  <<: *default
  database: rooms_test

production:
  adapter: postgresql
  encoding: unicode
  collation: en_US.UTF-8
  host: localhost
  database: rooms_production
  username: deploy2
  password: '123456'
  pool: 5
