default: &default
  adapter: postgresql
  encoding: unicode
  collation: en_US.UTF-8
  pool: 5
  username: postgres
  password: ''
  host: localhost
  port: 5432

development:
  <<: *default
  database: rooms_dev

test:
  <<: *default
  database: rooms_test

production:
  adapter: postgresql
  encoding: unicode
  collation: en_US.UTF-8
  host: 192.168.1.201
  database: rooms_production
  username: postgres
  password: 123456
  pool: 5
